//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace il_Topolino.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TopolinoEntities3 : DbContext
    {
        public TopolinoEntities3()
            : base("name=TopolinoEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basismenu> Basismenu { get; set; }
        public virtual DbSet<GekozenToppings> GekozenToppings { get; set; }
        public virtual DbSet<Gerecht_categorie> Gerecht_categorie { get; set; }
        public virtual DbSet<Gerechten> Gerechten { get; set; }
        public virtual DbSet<Ingredienten> Ingredienten { get; set; }
        public virtual DbSet<Klant> Klant { get; set; }
        public virtual DbSet<Orderdetails> Orderdetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Orderstatus> Orderstatus { get; set; }
        public virtual DbSet<Orderuitgifte> Orderuitgifte { get; set; }
        public virtual DbSet<Samenstelling> Samenstelling { get; set; }
        public virtual DbSet<Voertuig> Voertuig { get; set; }
    }
}
