//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace il_Topolino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetails
    {
        public int orderdetails_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> gerecht_id { get; set; }
    }
}
