//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace il_Topolino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voertuig
    {
        public int voertuig_id { get; set; }
        public string voertuig1 { get; set; }
        public int snelheid { get; set; }
        public string type { get; set; }

    }
}
